"""empty message

Revision ID: f27edb653509
Revises: 
Create Date: 2016-11-17 15:40:42.606537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27edb653509'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_name', sa.String(length=64), nullable=True))
    op.drop_column('users', 'nickname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(length=80), nullable=True))
    op.drop_column('users', 'real_name')
    ### end Alembic commands ###
